travis: reject invalid UUIDs (#836)
* travis: reject invalid UUIDs

Want to prevent any invalid UUIDs from being entered.

Want to put this in configlet lint, but can't:
https://github.com/exercism/configlet/issues/99
https://github.com/exercism/configlet/pull/168
So it will go in individual tracks' .travis.yml for now.

It appears that the site will accept pretty much arbitrary strings as
UUIDs for now, but we want to make less work for ourselves when valid
UUIDs are required.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -53,6 +53,16 @@ script:
         exit 1
     fi
  - |
+   # Check for invalid UUIDs.
+   # can be removed once `configlet lint` gains this ability.
+   # Check issue https://github.com/exercism/configlet/issues/99
+   bad_uuid=$(jq --raw-output '.exercises | map(.uuid) | .[]' config.json | grep -vE '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
+   if [ -n "$bad_uuid" ]; then
+     echo "invalid UUIDs found! please correct these to be valid UUIDs:"
+     echo "$bad_uuid"
+     exit 1
+   fi
+ - |
     set -e
 
     configlet lint .          # Check basic track configuration.
